<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>log</string>
	</array>
	<key>name</key>
	<string>ATG</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>^(\*{4} )([Tt](race|RACE))</string>
			<key>contentName</key>
			<string>entity.trace.message.atg</string>
			<key>end</key>
			<string>^(?=\*{4})</string>
			<key>name</key>
			<string>entity.trace.atg</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#logmessage</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>^(\*{4} )([Dd](ebug|EBUG))</string>
			<key>contentName</key>
			<string>entity.debug.message.atg</string>
			<key>end</key>
			<string>^(?=\*{4})</string>
			<key>name</key>
			<string>entity.debug.atg</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#logmessage</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>^(\*{4} )?([Ii]nfo)</string>
			<key>contentName</key>
			<string>entity.info.message.atg</string>
			<key>end</key>
			<string>^(?=\*{4})</string>
			<key>name</key>
			<string>entity.info.atg</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#logmessage</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>^(\*{4} )?(Warn)</string>
			<key>contentName</key>
			<string>entity.warn.message.atg</string>
			<key>end</key>
			<string>^(?=\*{4})</string>
			<key>name</key>
			<string>entity.warn.atg</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#logmessage</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>^(\*{4} )?(Error)</string>
			<key>contentName</key>
			<string>entity.error.message.atg</string>
			<key>end</key>
			<string>^(?=\*{4})</string>
			<key>name</key>
			<string>entity.error.atg</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#logmessage</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>^((\d{4}-\d{2}-\d{2} )|(\d{2}/\d{2}/\d{4}) )?(\d{2}:\d{2}:\d{2},\d{3}) ?INFO +(\[[^\[\]]+\])?( \([^\)]+\))? DEBUG</string>
			<key>beginCaptures</key>
			<dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>support.class.component</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>entity.debug.message.atg</string>
			<key>end</key>
			<string>^(?=(((\d{4}-\d{2}-\d{2} )|(\d{2}/\d{2}/\d{4}) )?(\d{2}:\d{2}:\d{2},\d{3}) ?))</string>
			<key>name</key>
			<string>entity.debug.atg</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#logmessage</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>^((\d{4}-\d{2}-\d{2} )|(\d{2}/\d{2}/\d{4}) )?(\d{2}:\d{2}:\d{2},\d{3}) ?TRACE +(\[[^\[\]]+\])?</string>
			<key>beginCaptures</key>
			<dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>support.class.component</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>entity.trace.message.atg</string>
			<key>end</key>
			<string>^(?=(((\d{4}-\d{2}-\d{2} )|(\d{2}/\d{2}/\d{4}) )?(\d{2}:\d{2}:\d{2},\d{3}) ?))</string>
			<key>name</key>
			<string>entity.trace.atg</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#logmessage</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>^((\d{4}-\d{2}-\d{2} )|(\d{2}/\d{2}/\d{4}) )?(\d{2}:\d{2}:\d{2},\d{3}) ?DEBUG +(\[[^\[\]]+\])?</string>
			<key>beginCaptures</key>
			<dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>support.class.component</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>entity.debug.message.atg</string>
			<key>end</key>
			<string>^(?=(((\d{4}-\d{2}-\d{2} )|(\d{2}/\d{2}/\d{4}) )?(\d{2}:\d{2}:\d{2},\d{3}) ?))</string>
			<key>name</key>
			<string>entity.debug.atg</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#logmessage</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>^((\d{4}-\d{2}-\d{2} )|(\d{2}/\d{2}/\d{4}) )?(\d{2}:\d{2}:\d{2},\d{3}) ?WARN +(\[[^\[\]]+\])?</string>
			<key>beginCaptures</key>
			<dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>support.class.component</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>entity.warn.message.atg</string>
			<key>end</key>
			<string>^(?=(((\d{4}-\d{2}-\d{2} )|(\d{2}/\d{2}/\d{4}) )?(\d{2}:\d{2}:\d{2},\d{3}) ?))</string>
			<key>name</key>
			<string>entity.warn.atg</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#logmessage</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>^((\d{4}-\d{2}-\d{2} )|(\d{2}/\d{2}/\d{4}) )?(\d{2}:\d{2}:\d{2},\d{3}) ?ERROR +(\[[^\[\]]+\])?</string>
			<key>beginCaptures</key>
			<dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>support.class.component</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>entity.error.message.atg</string>
			<key>end</key>
			<string>^(?=(((\d{4}-\d{2}-\d{2} )|(\d{2}/\d{2}/\d{4}) )?(\d{2}:\d{2}:\d{2},\d{3}) ?))</string>
			<key>name</key>
			<string>entity.error.atg</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#logmessage</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>^((\d{4}-\d{2}-\d{2} )|(\d{2}\/\d{2}\/\d{4}) )?(\d{2}:\d{2}:\d{2},\d{3}) ?INFO +(\[[^\[\]]+\])?( \([^\)]+\))? \*{4} Error</string>
			<key>beginCaptures</key>
			<dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>support.class.component</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>entity.error.message.atg</string>
			<key>end</key>
			<string>^(?=(((\d{4}-\d{2}-\d{2} )|(\d{2}/\d{2}/\d{4}) )?(\d{2}:\d{2}:\d{2},\d{3}) ?))</string>
			<key>name</key>
			<string>entity.error.atg</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#logmessage</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>^((\d{4}-\d{2}-\d{2} )|(\d{2}/\d{2}/\d{4}) )?(\d{2}:\d{2}:\d{2},\d{3}) ?INFO +(\[[^\[\]]+\])? (\** Error)</string>
			<key>beginCaptures</key>
			<dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>support.class.component</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>entity.error.message.atg</string>
			<key>end</key>
			<string>^(?=(((\d{4}-\d{2}-\d{2} )|(\d{2}/\d{2}/\d{4}) )?(\d{2}:\d{2}:\d{2},\d{3}) ?))</string>
			<key>name</key>
			<string>entity.error.atg</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#logmessage</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>^((\d{4}-\d{2}-\d{2} )|(\d{2}/\d{2}/\d{4}) )?(\d{2}:\d{2}:\d{2},\d{3}) ?INFO +(\[[^\[\]]+\])?</string>
			<key>beginCaptures</key>
			<dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>support.class.component</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>entity.info.message.atg</string>
			<key>end</key>
			<string>^(?=(((\d{4}-\d{2}-\d{2} )|(\d{2}/\d{2}/\d{4}) )?(\d{2}:\d{2}:\d{2},\d{3}) ?))</string>
			<key>name</key>
			<string>entity.info.atg</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#logmessage</string>
				</dict>
			</array>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>commerceObjects</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(order) ([^ .:\[\]]+)</string>
					<key>name</key>
					<string>keyword.atg.order</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(orderPriceInfo):([^ .:\[\]]+)</string>
					<key>name</key>
					<string>keyword.atg.orderPriceInfo</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>variable.parameter</string>
						</dict>
					</dict>
					<key>match</key>
					<string>\[([\w\d]+)\]</string>
					<key>name</key>
					<string>keyword.atg.id</string>
				</dict>
			</array>
		</dict>
		<key>components</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>support.class.component.name</string>
						</dict>
					</dict>
					<key>match</key>
					<string>[\t| ]((/\b[^ \t]+)+)(/\b[^ \t]+)</string>
					<key>name</key>
					<string>support.class.component</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>support.class.component.name</string>
						</dict>
						<key>6</key>
						<dict>
							<key>name</key>
							<string>keyword</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(\[)(([a-zA-Z]+\.)+)(([a-zA-Z])+)(\])</string>
					<key>name</key>
					<string>support.class.component</string>
				</dict>
			</array>
		</dict>
		<key>keywords</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\[|\]|\{|\}|=|:|,|;|&amp;|\(|\)</string>
					<key>name</key>
					<string>keyword</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b[Ss][Kk][Uu]\b( |:|=)</string>
					<key>name</key>
					<string>keyword.atg.sku</string>
				</dict>
			</array>
		</dict>
		<key>logmessage</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#stacktrace</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#sqldebug</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#value</string>
				</dict>
			</array>
		</dict>
		<key>pipeline</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>entity.name.tag.chain</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(Done )?(Executing Chain: )(\b.*\b)</string>
					<key>name</key>
					<string>constant.language.chain</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>variable.parameter.link</string>
						</dict>
					</dict>
					<key>match</key>
					<string>Executing link: (\b.*\b)</string>
					<key>name</key>
					<string>constant.language.link</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.tag.chain</string>
						</dict>
					</dict>
					<key>match</key>
					<string>Last processor in chain, (stopping) chain execution for chain: (\b.*\b)</string>
					<key>name</key>
					<string>constant.language.link.last</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>variable.parameter.link</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>storage.link.return</string>
						</dict>
					</dict>
					<key>match</key>
					<string>Link (\b.*\b) return value: (\d+)</string>
					<key>name</key>
					<string>constant.language.link</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.link.return</string>
						</dict>
					</dict>
					<key>match</key>
					<string>PipelineResult has (\d+) errors</string>
					<key>name</key>
					<string>constant.language.chain</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.transaction</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(TX_.*\b)</string>
					<key>name</key>
					<string>support</string>
				</dict>
			</array>
		</dict>
		<key>sqldebug</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\[\+\+SQLQuery\+\+\]</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>string</string>
						</dict>
					</dict>
					<key>contentName</key>
					<string>string</string>
					<key>end</key>
					<string>\[--SQLQuery--\]</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>string</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>source.sql</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>\[\+\+SQLSelect\+\+\]</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>string</string>
						</dict>
					</dict>
					<key>contentName</key>
					<string>string</string>
					<key>end</key>
					<string>\[--SQLSelect--\]</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>string</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>source.sql</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>stacktrace</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#stacktrace_keywords</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#stacktrace_container</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#stacktrace_at</string>
				</dict>
			</array>
		</dict>
		<key>stacktrace_at</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.error.keyword.stacktrace</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>constant.language.class.stacktrace</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.stacktrace</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.stacktrace</string>
				</dict>
				<key>7</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.stacktrace</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>entity.error.message.stacktrace</string>
			<key>match</key>
			<string>(at) ([^\(]+)\.([^\.]+)\.([^\.]+)(\((\w+\.\w+):(\d+)\))</string>
			<key>name</key>
			<string>entity.error.message.stacktrace</string>
		</dict>
		<key>stacktrace_container</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>constant.language.class</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>entity.error.message.stacktrace</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(CONTAINER:)([\w\.]+)(;|:([^;:]+;))</string>
			<key>name</key>
			<string>meta.structure.object.stacktrace.container</string>
		</dict>
		<key>stacktrace_keywords</key>
		<dict>
			<key>match</key>
			<string>Caused by|SOURCE:</string>
			<key>name</key>
			<string>keyword.stacktrace</string>
		</dict>
		<key>value</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#pipeline</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#components</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#keywords</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#commerceObjects</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#keyvalue</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>text.atg</string>
	<key>uuid</key>
	<string>59d2eab0-506c-4c33-8e2f-a6a74820383a</string>
</dict>
</plist>
