<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>txt</string>
		<string>notes</string>
	</array>
	<key>name</key>
	<string>Notes</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#notes</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>all</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>comment</key>
					<string>Urls</string>
					<key>match</key>
					<string>(([a-zA-Z]{3,6}3?\:\/\/)?([-a-zA-Z0-9@:%._\+~#=]{2,256}\.[a-z]{2,6}\b([-a-zA-Z0-9@:%_\+.~#?&amp;//=]*)))</string>
					<key>name</key>
					<string>support.class.notes</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>Comments</string>
					<key>match</key>
					<string>(?&lt;!\:)(\/\/.*)</string>
					<key>name</key>
					<string>comment.notes</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>Line breaks</string>
					<key>match</key>
					<string>^(\-[\-\=]{2}.*)</string>
					<key>name</key>
					<string>support.function.notes</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword.other.notes</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>Ordered bullets</string>
					<key>match</key>
					<string>^([ \t]*[0-9a-z]+[\:\.\)]\)?\s(\w+\:)?)</string>
					<key>name</key>
					<string>keyword.operator.notes</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword.other.notes</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>Unordered bullets</string>
					<key>match</key>
					<string>^(\t*[\-\=\.]+\s(\w+\:)?)</string>
					<key>name</key>
					<string>variable.language.notes</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>Emphasis</string>
					<key>match</key>
					<string>(\*+[^\*]+\*+)</string>
					<key>name</key>
					<string>keyword.other.notes</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>Arrows</string>
					<key>match</key>
					<string>(-+&gt;||=+&gt;||&lt;=+||&lt;-+)</string>
					<key>name</key>
					<string>variable.language.notes</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>Headers</string>
					<key>match</key>
					<string>^([A-Z].*\:)$</string>
					<key>name</key>
					<string>entity.name.tag.notes</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>Proper headers</string>
					<key>match</key>
					<string>^([-=]+\s?\w[\w\s]*[\-=]+)</string>
					<key>name</key>
					<string>entity.name.tag.notes</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>Single Quotes</string>
					<key>match</key>
					<string>(\"[^\"]*\")</string>
					<key>name</key>
					<string>string.quoted.double.notes</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>Top-level vocab definitions</string>
					<key>match</key>
					<string>^((\w+\s?\w*\:)(?=[ \t][\w\d]))</string>
					<key>name</key>
					<string>keyword.other.notes</string>
				</dict>
			</array>
		</dict>
		<key>highlights</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>markup.bold</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>done</string>
					<key>match</key>
					<string>^.*(#DONE)</string>
					<key>name</key>
					<string>comment.notes</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>brackets</string>
					<key>match</key>
					<string>\[[a-zA-Z0-9 ]+\]</string>
					<key>name</key>
					<string>support.function</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>Warning critical</string>
					<key>match</key>
					<string>(!!.*!!)</string>
					<key>name</key>
					<string>entity.error.atg</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>Warning critical</string>
					<key>match</key>
					<string>(!!.*$)</string>
					<key>name</key>
					<string>entity.error.atg</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>Important, surrounded by &lt;...&gt;</string>
					<key>match</key>
					<string>(\&lt;[^\&gt;]*\&gt;)</string>
					<key>name</key>
					<string>constant.other.date.notes</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(HYP:.*$)</string>
					<key>name</key>
					<string>entity.other.inherited-class</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(#\d+)</string>
					<key>name</key>
					<string>variable.parameter</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(#[^ ]+)</string>
					<key>name</key>
					<string>markup.bold</string>
				</dict>
			</array>
		</dict>
		<key>keywords</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>TBD|TBC|TODO|FIXME|TBA|DONE|null|NULL</string>
					<key>name</key>
					<string>keyword</string>
				</dict>
			</array>
		</dict>
		<key>languages</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(\[)(sql|dml|ddl|mysql)(\])</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>string.regexp.notes</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>markup.bold.notes</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>string.regexp.notes</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>SQL</string>
					<key>end</key>
					<string>(\[)(\\?\/?(end|sql|dml|ddl|mysql))(\])</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>string.regexp.notes</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>markup.bold.notes</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>string.regexp.notes</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>source.sql</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(\[)(xml|tld|jsp|pt|cpt|dtml|rss|opml)(\])</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>string.regexp.notes</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>markup.bold.notes</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>string.regexp.notes</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>XML</string>
					<key>end</key>
					<string>(\[)(\\?\/?(end|xml|tld|jsp|pt|cpt|dtml|rss|opml))(\])</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>string.regexp.notes</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>markup.bold.notes</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>string.regexp.notes</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>text.xml</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(\[)(atg)(\])</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>string.regexp.notes</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>markup.bold.notes</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>string.regexp.notes</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>ATG</string>
					<key>end</key>
					<string>(\[)(\\?\/?(atg))(\])</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>string.regexp.notes</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>markup.bold.notes</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>string.regexp.notes</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>text.atg</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>lists</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>^[\t ]*#</string>
					<key>end</key>
					<string>$</string>
					<key>name</key>
					<string>markup.bold</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#notes</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>^[\t ]*-</string>
					<key>end</key>
					<string>$</string>
					<key>name</key>
					<string>string.bullet</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#notes</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>^[\t ]*&gt;&gt;&gt;</string>
					<key>end</key>
					<string>$</string>
					<key>name</key>
					<string>support.function</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#notes</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>^[\t ]*&gt;&gt;</string>
					<key>end</key>
					<string>$</string>
					<key>name</key>
					<string>entity.name.class</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#notes</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>^[\t ]*&gt;</string>
					<key>end</key>
					<string>$</string>
					<key>name</key>
					<string>markdown.heading</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#notes</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>match</key>
					<string>^[\t ]*\*\).*$</string>
					<key>name</key>
					<string>string.bullet</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>^[\t ]*o</string>
					<key>end</key>
					<string>$</string>
					<key>name</key>
					<string>support.function</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#notes</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>notes</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#languages</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#keywords</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#titles</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#highlights</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#lists</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#sentences</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#symbols</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#all</string>
				</dict>
			</array>
		</dict>
		<key>question</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>()</string>
					<key>name</key>
					<string>keyword</string>
				</dict>
			</array>
		</dict>
		<key>sentences</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#question</string>
				</dict>
			</array>
		</dict>
		<key>symbols</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>-&gt;</string>
					<key>name</key>
					<string>markdown.heading</string>
				</dict>
				<dict>
					<key>match</key>
					<string>:\(</string>
					<key>name</key>
					<string>other.remove</string>
				</dict>
			</array>
		</dict>
		<key>titles</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>^={1}.*$</string>
					<key>name</key>
					<string>entity.name.class</string>
				</dict>
				<dict>
					<key>match</key>
					<string>^={2}.*$</string>
					<key>name</key>
					<string>entity.name.class</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.notes</string>
	<key>uuid</key>
	<string>b9bf3970-f517-46fd-a7f8-ae78fd761f84</string>
</dict>
</plist>
